import React, { useMemo } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import Seo from '../components/Seo';
import { buildBenchmarkView, metricDefinitions, rankMetricRows } from './content/benchmark';

const format = (value, metric) => metric === 'cost' ? `$${value.toFixed(3)}` : metric === 'latency' ? `${value.toFixed(1)} min` : metric === 'reliability' ? `${value.toFixed(1)}%` : value.toFixed(1);
const chartMetrics = ['performance', 'cost', 'latency'];
const detailMetrics = ['performance', 'cost', 'latency', 'reliability'];

const ResearchOverview = () => {
  const [params, setParams] = useSearchParams();
  const taskGroup = params.get('task') || 'All tasks';
  const metric = params.get('metric') || 'performance';
  const view = useMemo(() => buildBenchmarkView({ taskGroup, metric, sort: metric }), [taskGroup, metric]);
  const update = (changes) => { const next = new URLSearchParams(params); Object.entries(changes).forEach(([key, value]) => value && value !== 'All tasks' ? next.set(key, value) : next.delete(key)); setParams(next); };
  return <><Seo title="Agentic Test & Validation | Plotune Research" description="Visual comparisons for agentic engineering test and validation workflows." path="/research" />
    <section className="research-page benchmark-page"><header className="page-heading"><span className="section-label">Benchmark</span><h1>Agentic Test &amp; Validation</h1><p>Visual comparisons for engineering workflows, designed to make performance, cost, time, and reliability legible before the detailed results.</p></header><div className="benchmark-layout"><aside className="workflow-side-nav"><span className="section-label">Workflow</span>{view.taskGroups.map((task) => <button key={task} className={task === taskGroup ? 'active' : ''} onClick={() => update({ task })}>{task === 'All tasks' ? 'Overall index' : task}</button>)}</aside><div className="benchmark-canvas"><section className="highlights" aria-labelledby="highlights-title"><div className="highlights-heading"><div><span className="section-label">Highlights</span><h2 id="highlights-title">Leading models at a glance</h2></div><span>{taskGroup === 'All tasks' ? 'Overall index' : taskGroup}</span></div><div className="highlight-chart-grid">{chartMetrics.map((key) => <MetricBarChart key={key} rows={view.rows} metric={key} onSelect={() => update({ metric: key })} active={metric === key} />)}</div></section><section className="metric-detail" aria-labelledby="metric-title"><div className="metric-tabs-list" role="tablist">{detailMetrics.map((key) => <button key={key} className={metric === key ? 'active' : ''} onClick={() => update({ metric: key })}>{metricDefinitions[key].label}</button>)}</div><div className="ranked-chart-panel"><div className="ranked-chart-heading"><div><span className="section-label">{taskGroup === 'All tasks' ? 'Overall index' : taskGroup}</span><h2 id="metric-title">{metricDefinitions[metric]?.label} across models</h2><p>{metric === 'performance' ? 'Task-normalized score. Higher is better.' : metric === 'cost' ? 'Average cost per completed task. Lower is better.' : metric === 'latency' ? 'Average task duration. Lower is better.' : 'Completed runs with a valid terminal result. Higher is better.'}</p></div><span>Top 12</span></div><RankedBarChart rows={rankMetricRows(view.rows, metric, 12)} metric={metric} /></div></section><Link className="results-link" to={`/research/results?${params.toString()}`}>View all model results</Link></div></div>
    </section></>;
};

const MetricBarChart = ({ rows, metric, onSelect, active }) => { const config = metricDefinitions[metric]; const cohort = rankMetricRows(rows, metric, 8); const values = cohort.map((row) => row[config.key]); const min = Math.min(...values); const max = Math.max(...values); const width = (value) => max === min ? 82 : 32 + ((config.higher ? value - min : max - value) / (max - min)) * 64; return <button className={active ? 'metric-card active' : 'metric-card'} onClick={onSelect}><header><div><span className="metric-swatch" /><h3>{metric === 'performance' ? 'Validation index' : metric === 'cost' ? 'Cost per task' : 'Time per task'}</h3></div><small>{config.higher ? 'Higher is better' : 'Lower is better'}</small></header><div className="mini-bars">{cohort.map((row) => <div key={row.model} className="mini-bar-row"><span title={row.model}>{row.modelName}</span><b><i style={{ width: `${width(row[config.key])}%`, backgroundColor: row.color }} /></b><strong>{format(row[config.key], metric)}</strong></div>)}</div></button>; };
const RankedBarChart = ({ rows, metric }) => { const config = metricDefinitions[metric]; const values = rows.map((row) => row[config.key]); const min = Math.min(...values); const max = Math.max(...values); const width = (value) => max === min ? 82 : 18 + ((config.higher ? value - min : max - value) / (max - min)) * 78; return <div className="ranked-bars" role="img" aria-label={`Top ${rows.length} models ranked by ${config.label}`}>{rows.map((row, index) => <div className="ranked-bar-row" key={row.model}><span className="chart-rank">{index + 1}</span><span className="chart-model"><i style={{ backgroundColor: row.color }} />{row.model}</span><div className="bar-track"><b style={{ width: `${width(row[config.key])}%`, backgroundColor: row.color }}><em>{format(row[config.key], metric)}</em></b></div></div>)}</div>; };
export default ResearchOverview;
