import React,{useEffect,useState}from'react';import{useParams,Link}from'react-router-dom';import{MDXProvider}from'@mdx-js/react';import Seo from'../components/Seo';import ResearchPlot from'../components/research/ResearchPlot';import FlowDiagram from'../components/research/FlowDiagram';import StatFigure from'../components/research/StatFigure';import{Insight,StudyMeta}from'../components/research/ResearchBlocks';import{getResearchArticle}from'./content/articles';import{getSolutionSegment}from'../content/solutions';import{captureFunnelTouch,withFunnelParams}from'../utils/funnel';
// An article's CTA target is either explicit (article.cta = {path, summary, label}, for
// destinations outside the /solutions/* segment system, e.g. /nexus or the pillar page) or
// derived from article.segment when it matches a src/content/solutions.js key.
const resolveCta=(article)=>{if(article.cta)return article.cta;const solution=getSolutionSegment(article.segment);return solution&&{path:`/solutions/${solution.slug}`,summary:`${solution.label}: ${solution.heroTitle}`,label:'See how this workflow can be automated'};};
// A short analytics tag (can/ros/orchestration/hil/agentic-dev) for traffic-source tools —
// article.tag wins when set explicitly, else it's derived from the linked segment's own tag.
const resolveTag=(article)=>article.tag||getSolutionSegment(article.segment)?.tag;
const ResearchArticle=()=>{const{slug}=useParams();const article=getResearchArticle(slug);const[Content,setContent]=useState(null);const[loadError,setLoadError]=useState(false);const[attempt,setAttempt]=useState(0);const cta=article&&resolveCta(article);const tag=article&&resolveTag(article);useEffect(()=>{if(!article)return;setLoadError(false);article.loader().then(module=>setContent(()=>module.default)).catch(()=>setLoadError(true));},[article,attempt]);useEffect(()=>{if(!article)return;captureFunnelTouch({article:article.slug,segment:article.segment});window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'research_article_view',tag,segment:article.segment||null,article:article.slug});},[article,tag]);if(!article)return <section className="research-page-head"><h1>Study not found</h1><p>This research item is not published.</p></section>;const components={Insight,ResearchPlot,FlowDiagram,StatFigure};return <><Seo title={`${article.title} | Plotune Research`} description={article.summary} path={`/research/articles/${article.slug}`} tag={tag}/><article className="research-article" data-plotune-tag={tag||undefined}><header><p>{article.topic}</p><h1>{article.title}</h1><StudyMeta article={article}/></header>{Content?<MDXProvider components={components}><Content article={article}/></MDXProvider>:loadError?<div className="research-load-error" role="alert"><p>We couldn’t load this study. Check your connection and try again.</p><button type="button" onClick={()=>setAttempt(a=>a+1)}>Retry</button></div>:<p role="status">Loading study…</p>}{cta&&<div className="research-article-cta"><p>{cta.summary}</p><Link to={withFunnelParams(cta.path,{article:article.slug,segment:article.segment})}>{cta.label} →</Link></div>}</article></>};export default ResearchArticle;


