/* Auth transitions use intercepted responses; no account is created or email sent. */
const fs=require('fs'),path=require('path'),{chromium}=require('playwright'),{fixtures}=require('./browser.cjs');
const out='docs/redesign/evidence/auth-success';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch();let results=[],checks=[];for(const [device,width,height] of [['mobile',390,844],['tablet',768,1024],['desktop',1440,900]]){const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce'});await fixtures(context,false);await context.route('**/login',r=>new URL(r.request().url()).hostname==='api.plotune.net'?r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({access_token:'qa-local',token_type:'Bearer'})}):r.fallback());const page=await context.newPage();const save=async(name)=>{await page.waitForTimeout(150);await page.evaluate(()=>window.scrollTo(0,0));const file=name+'-'+device+'.png';await page.screenshot({path:path.join(out,file),fullPage:true});results.push({device,file})};
await page.goto('http://localhost:4184/register');for(const [name,value]of Object.entries({fullName:'Local QA',email:'qa@example.test',username:'qa-engineer',password:'LocalQa123!',confirmPassword:'LocalQa123!'}))await page.locator('[name="'+name+'"]').fill(value);await page.locator('[name="sector"]').selectOption('engineering');await page.locator('[name="country"]').selectOption('turkey');await page.locator('#terms').check();await page.getByRole('button',{name:/create account/i}).click();await page.getByRole('heading',{name:'Check your email'}).waitFor();await save('registration-check-email');checks.push({device,name:'registration enters pending verification',ok:await page.getByText('Open the verification link in your email for qa@example.test.').count()>0});
await page.goto('http://localhost:4184/verify-email?token=qa-local');await page.getByRole('heading',{name:'Email Verified!'}).waitFor();await save('email-verified');await page.waitForURL('**/login');checks.push({device,name:'verification success redirects to login',ok:true});
await page.goto('http://localhost:4184/reset-password');await page.locator('input[type="email"]').fill('qa@example.test');await page.getByRole('button',{name:/send/i}).first().click();await page.getByRole('heading',{name:'Enter Verification Code'}).waitFor();await page.getByPlaceholder('000000000').fill('123456789');await page.getByRole('button',{name:/verify code/i}).click();await page.getByPlaceholder('Create a strong password').waitFor();await save('password-reset-new-password');await page.getByPlaceholder('Create a strong password').fill('LocalQa123!');await page.getByPlaceholder('Confirm your password').fill('LocalQa123!');await page.getByRole('button',{name:/reset password/i}).click();await page.waitForURL('**/login');checks.push({device,name:'password reset completes mocked flow',ok:true});
await page.locator('#login-username').fill('qa-engineer');await page.locator('#login-password').fill('LocalQa123!');await page.getByRole('button',{name:'Login',exact:true}).click();await page.waitForURL('**/dashboard');await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();await save('login-dashboard');checks.push({device,name:'login validates mocked token and opens dashboard',ok:true});await context.close()}
await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify(checks,null,2));console.log(checks.length+' checks; '+results.length+' screenshots');if(checks.some(c=>!c.ok))process.exitCode=1})().catch(e=>{console.error(e);process.exit(1)});
