import React from 'react';
import { Link } from 'react-router-dom';
import Seo from '../components/Seo';
import EngineeringDiagram from '../components/EngineeringDiagram';
import { posthog } from '../posthog';
import { useCtaTracking } from '../utils/ctaTracking';
import { getFunnelContext, withFunnelParams } from '../utils/funnel';
const interfaces = [
 ['CAN / CAN FD', 'Linux CAN transports for bus interaction and capture.'],
 ['UART', 'Serial interfaces, including RS-485 and modem-control lines.'],
 ['XCP', 'CAN and Ethernet transports with different supported operations.'],
 ['UDS / DoIP', 'Diagnostics through reachable network and CAN transports.'],
 ['ROS 2 / DDS', 'Join an existing DDS domain, discover topics and record evidence.'],
];
export default function Nexus() {
 const heroAssessmentCta=useCtaTracking('nexus_hero_assessment');
 const bottomContactCta=useCtaTracking('nexus_bottom_contact');
 return <main className="nexus-design"><Seo title="Plotune Nexus: Local-First Appliance for AI-Ready Test Systems" description="Plotune Nexus is a managed, local-first appliance that connects to real test systems and runs bounded, AI-ready workflows over a standard MCP surface, with data that stays yours." path="/nexus" />
 <section className="design-container nexus-intro"><div className="section-index"><span>Plotune Nexus / Local-first appliance</span><span>Hardware + software</span></div><div className="product-spread"><div className="product-copy"><p className="technical-label">The agent meets the bench.</p><h1>Real hardware.<br /><span>Controlled operations.</span></h1><p>Nexus connects AI agents to physical engineering and test systems through MCP. Hardware interaction and first-write artifacts happen on the appliance; cloud services support routing, identity and export.</p><div className="design-actions"><div><Link className="design-button" to={withFunnelParams('/ai-readiness')} ref={heroAssessmentCta.ref} onClick={()=>posthog.capture('nexus_assessment_clicked',{...getFunnelContext(),path:'/nexus'})}>Check Your AI Readiness ↗</Link><p className="action-note">4 quick questions · about 30 seconds · no sign-up</p></div><Link className="text-link" to="/nexus/connectivity">See How It Connects →</Link></div></div><figure className="hardware-plate"><span className="technical-label">NEXUS / hardware overview</span><img src="/assets/plotune-nexus.webp" width="1088" height="725" loading="lazy" decoding="async" alt="Plotune Nexus appliance with a finned enclosure and physical connectors" /><figcaption>Plotune-defined hardware. Pre-integrated software. Managed lifecycle.</figcaption></figure></div></section>
 <section className="design-container nexus-architecture"><div className="section-index"><span>01 / System architecture</span><span>Request, operation, evidence</span></div><h2>One controlled surface.<br />A physical result.</h2><EngineeringDiagram interactive /><p className="diagram-note">Conceptual flow. Available operations depend on transport, connected hardware, access and configuration.</p></section>
 <section className="design-container interface-section"><div className="section-index"><span>02 / Engineering interfaces</span><Link to="/docs/nexus/hardware-compatibility">Compatibility matrix ↗</Link></div><div className="interface-layout"><div><h2>Speak the language<br />of your system.</h2><p>Use the supported transports on your bench, rig or vehicle. Check the documented native, container and scale-up tiers before choosing hardware.</p><Link className="text-link" to="/nexus/connectivity">Explore connectivity →</Link></div><dl className="interface-list">{interfaces.map(([name,copy],i)=><div key={name}><span className="technical-label">0{i+1}</span><dt>{name}</dt><dd>{copy}</dd></div>)}</dl></div></section>
 <section className="nexus-workflow"><div className="design-container"><div className="section-index"><span>03 / From requirement to evidence</span><span>A bounded workflow</span></div><h2>Discover. Execute.<br />Record what happened.</h2><ol className="workflow-sequence"><li><span>01</span><h3>Inspect the system</h3><p>Discover the available interfaces and current state before requesting an operation.</p></li><li><span>02</span><h3>Run a bounded operation</h3><p>Use the relevant MCP tools and job controls within the configured access and execution limits.</p></li><li><span>03</span><h3>Keep the evidence</h3><p>Return status, metadata and retrieval paths for locally recorded logs, traces and artifacts.</p></li></ol><div className="workflow-links"><Link to="/solutions/can-ecu-testing">CAN / ECU testing ↗</Link><Link to="/solutions/ros2-dds-testing">ROS 2 / DDS testing ↗</Link><Link to="/nexus/stream">Stream integration ↗</Link><Link to="/nexus/use-cases">View Use Cases ↗</Link></div></div></section>
 <section className="design-container nexus-boundary"><p className="technical-label">04 / Read the engineering details</p><div className="research-spread"><h2>Know the boundary.</h2><div><p>Local-first operation is documented alongside cloud dependencies, hardware compatibility and current constraints. Start with the architecture and security model.</p><Link className="text-link" to="/docs/nexus">Read the Nexus documentation →</Link><div className="boundary-links"><Link to="/docs/nexus/security-model">Security model ↗</Link><Link to="/docs/nexus/data-handling">Data handling ↗</Link><Link to="/docs/nexus/protocols">Protocols ↗</Link></div></div></div></section>
 <section className="closing-section design-container"><p className="technical-label">Start with your test environment</p><h2>Map Nexus<br />to your bench.</h2><p>Tell us about your hardware, interfaces and first workflow.</p><div className="design-actions"><Link className="design-button" ref={bottomContactCta.ref} to={withFunnelParams('/contact')}>Get Your Integration Plan ↗</Link><Link className="text-link" to="/nexus/use-cases">View Use Cases →</Link></div></section></main>;
}
