/* Production-build QA with isolated fixtures; never sends leads or analytics to production. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');const {fixtures}=require('./redesign/browser.cjs');
const root=path.resolve('build'),out=path.resolve('docs/redesign/evidence/stream-early-access');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let file=path.join(root,new URL(req.url,'http://localhost').pathname);if(!path.extname(file))file=path.join(file,'index.html');if(!fs.existsSync(file))file=path.join(root,'index.html');res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{
 await new Promise(resolve=>server.listen(4190,'127.0.0.1',resolve));const browser=await chromium.launch();const results=[];
 for(const [device,width,height] of [['desktop',1440,900],['mobile',390,844]]){
  const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce'});await fixtures(context,false);const page=await context.newPage();page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
  let fail=true,payloads=[];await page.route('https://script.google.com/**',async route=>{payloads.push(JSON.parse(route.request().postData()));await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:!fail})});});
  const save=async state=>{await page.screenshot({path:path.join(out,`${device}-${state}.png`),fullPage:state==='landing'});const info=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,url:location.pathname+location.search,dialog:!!document.querySelector('dialog.stream-invitation[open]'),focus:document.activeElement?.getAttribute('id')}));assert.equal(info.overflow,false,`${device}/${state}: horizontal overflow`);results.push({device,state,...info,errors:[...errors]});};
  const navigate=async name=>{if(width<768)await page.getByRole('button',{name:'Open workspace navigation',exact:true}).click();await page.getByRole('navigation',{name:'Workspace navigation',exact:true}).getByRole('button',{name,exact:true}).click();};
  await page.goto('http://localhost:4190/stream');await page.getByRole('link',{name:/Try the demo experience/}).first().waitFor();assert.ok(await page.locator('a[href="/stream/demo"]').count());await save('landing');
  await page.goto('http://localhost:4190/stream/demo');await page.getByRole('navigation',{name:'Workspace navigation',exact:true}).waitFor({state:'attached'});await save('initial');assert.equal(await page.locator('.stream-invitation').count(),0);
  if(width<768)await page.getByRole('button',{name:'Open workspace navigation',exact:true}).click();await page.getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('dialog',{name:'Create a project'}).getByLabel('Project name').fill('Early access QA');await page.getByRole('dialog',{name:'Create a project'}).getByRole('button',{name:'Create project'}).click();assert.equal(await page.locator('.stream-invitation').count(),0);
  await navigate('Events');await page.getByRole('dialog',{name:'Get early access to Stream.'}).waitFor();await save('events-modal');assert.equal(await page.locator('#stream-early-access-email').evaluate(el=>el===document.activeElement),true);
  await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');assert.ok(await page.evaluate(()=>document.querySelector('dialog.stream-invitation').contains(document.activeElement)));
  await page.getByRole('button',{name:'Not now',exact:true}).click();await save('dismissed');assert.ok(await page.locator('.stream-early-access-reopen').evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),'Floating icon must be unobscured');await navigate('Dashboards');assert.equal(await page.locator('.stream-invitation').count(),0);
  for(const name of ['Events','Dashboards','API setup','MCP setup','Webhooks','Project Settings']) { await navigate(name);assert.equal(await page.locator('.stream-invitation').count(),0); }
  await navigate('Dashboards');
  await page.getByRole('button',{name:'Reopen Stream early access invitation'}).click();await save('reopened');await page.getByLabel('Work email address').fill('engineer@example.test');await page.getByRole('button',{name:'Join the early access list',exact:true}).click();await page.getByRole('alert').filter({hasText:'couldn’t send'}).waitFor();await save('failure');assert.equal(await page.getByLabel('Work email address').inputValue(),'engineer@example.test');
  fail=false;await page.getByRole('button',{name:'Join the early access list',exact:true}).click();await page.getByText('You’re on the early access list. Keep exploring.').waitFor();await save('success');assert.ok(await page.locator('.stream-early-access-success').evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),'Success feedback must be unobscured');assert.equal(await page.locator('.stream-invitation,.stream-early-access-reopen').count(),0);assert.equal(payloads.length,2);assert.equal(payloads[0].submissionId,payloads[1].submissionId);assert.equal(payloads[0].kind,'contact');assert.equal(payloads[0].topic,'Plotune Stream Early Access');assert.ok(page.url().includes('view=dashboards'));
  await page.reload();assert.equal(await page.locator('.stream-invitation,.stream-early-access-reopen').count(),0);
  for(const name of ['Events','Dashboards','API setup','MCP setup','Webhooks','Project Settings'])await navigate(name);
  await context.close();
  const fresh=await browser.newContext({viewport:{width,height},reducedMotion:'reduce'});await fixtures(fresh,false);const dashboardPage=await fresh.newPage();await dashboardPage.goto('http://localhost:4190/stream/demo?view=dashboards');await dashboardPage.getByRole('navigation',{name:'Workspace navigation',exact:true}).waitFor({state:'attached'});assert.equal(await dashboardPage.locator('.stream-invitation').count(),0);
  if(width<768)await dashboardPage.getByRole('button',{name:'Open workspace navigation',exact:true}).click();await dashboardPage.getByRole('navigation',{name:'Workspace navigation',exact:true}).getByRole('button',{name:'Dashboards',exact:true}).click();await dashboardPage.getByRole('dialog',{name:'Get early access to Stream.'}).waitFor();await dashboardPage.screenshot({path:path.join(out,`${device}-dashboards-modal.png`)});await dashboardPage.keyboard.press('Escape');assert.equal(await dashboardPage.locator('.stream-invitation').count(),0);await fresh.close();
 }
 await browser.close();server.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));assert.ok(results.every(r=>r.errors.length===0),'Browser errors');console.log(`${results.length+2} screenshots; all browser assertions passed`);
})().catch(error=>{console.error(error);server.close();process.exit(1);});
